
version_application: "1.0.0"
environment: "production"


custom_lint_rules_version_application: "1.0.0"
custom_lint_rules_environment: "production"


---> oie tu role necesita anteponer el nombre del role en las variables
