- name: Ensure the httpd package is installed
  ansible.builtin.package:
    name: httpd
    state: present

- name: Create the index.html file
  ansible.builtin.template:
    src: files/index.html
    dest: /var/www/html/

- name: Start the httpd service if needed
  service:
    name: httpd
    state: started

- name: Allow HTTP service in firewall
  command:
    service: http
    permanent: true
    state: DISABLED
    immediate: true


